# Generated by Django 5.2.7 on 2025-11-04 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CottonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Farmer Name')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('driver_name', models.CharField(max_length=50, verbose_name='Driver Name')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='Vehicle Number')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('date_of_entry', models.DateTimeField(default=django.utils.timezone.now)),
                ('loaded_vehicle_weight', models.FloatField(verbose_name='Loaded Vehicle Weight (kg)')),
                ('unloading_vehicle_weight', models.FloatField(verbose_name='Unloading Vehicle Weight (kg)')),
                ('ginning_name', models.CharField(max_length=100, verbose_name='Ginning Name')),
                ('net_weight', models.FloatField(default=0, verbose_name='Net Weight (kg)')),
                ('date_of_unloading', models.DateTimeField(default=django.utils.timezone.now)),
                ('market_rate', models.FloatField(verbose_name='Market Rate (₹ per Quintal)')),
                ('bedding_rate', models.FloatField(verbose_name='Bedding Rate (₹ per Quintal)')),
                ('total_amount', models.FloatField(default=0, verbose_name='Total Amount (₹)')),
                ('advance_paid', models.FloatField(default=0, verbose_name='Advance Paid (₹)')),
                ('balance_amount', models.FloatField(default=0, verbose_name='Balance Amount (₹)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payment Received (Cash)')),
            ],
            options={
                'verbose_name': 'Cotton Data',
                'verbose_name_plural': 'Cotton Data',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, verbose_name='Invoice Number')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('customer_number', models.CharField(max_length=15, verbose_name='Customer Contact Number')),
                ('driver_name', models.CharField(max_length=50, verbose_name='Driver Name')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='Vehicle Number')),
                ('ginning_name', models.CharField(max_length=100, verbose_name='Ginning Name')),
                ('total_weight', models.FloatField(verbose_name='Total Weight (kg)')),
                ('cotton_weight', models.FloatField(verbose_name='Cotton Weight (kg)')),
                ('market_rate', models.FloatField(verbose_name='Market Rate (₹ per Quintal)')),
                ('bedding_rate', models.FloatField(verbose_name='Bedding Rate (₹ per Quintal)')),
                ('total_amount', models.FloatField(verbose_name='Total Amount (₹)')),
                ('advance_paid', models.FloatField(verbose_name='Advance Paid (₹)')),
                ('balance_amount', models.FloatField(verbose_name='Balance Amount (₹)')),
            ],
        ),
    ]
