# Generated by Django 5.2.7 on 2025-10-29 18:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Customer Data',
                'verbose_name_plural': 'Customer Data',
            },
        ),
        migrations.CreateModel(
            name='DriverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50, verbose_name='Driver Name')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='Vehicle Number')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('vehicle_weight', models.FloatField(verbose_name='Total Vehicle Weight (kg)')),
                ('date_of_entry', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Driver Data',
                'verbose_name_plural': 'Driver Data',
            },
        ),
        migrations.CreateModel(
            name='CottonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_rate', models.FloatField(verbose_name='Market Rate (₹ per Quintal)')),
                ('bedding_rate', models.FloatField(verbose_name='Bedding Rate (₹ per Quintal)')),
                ('total_amount', models.FloatField(verbose_name='Total Amount (₹)')),
                ('advance_paid', models.FloatField(default=0, verbose_name='Advance Paid (₹)')),
                ('balance_amount', models.FloatField(default=0, verbose_name='Balance Amount (₹)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payment Received (Cash)')),
                ('date_of_entry', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotton_entries', to='CottonApp.customerdata')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotton_deliveries', to='CottonApp.driverdata')),
            ],
            options={
                'verbose_name': 'Cotton Data',
                'verbose_name_plural': 'Cotton Data',
            },
        ),
        migrations.CreateModel(
            name='VehicleUnloadingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loaded_vehicle_weight', models.FloatField(verbose_name='Loaded Vehicle Weight (kg)')),
                ('Unloading_vehicle_weight', models.FloatField(verbose_name='Unloading Vehicle Weight (kg)')),
                ('ginning_Name', models.CharField(max_length=100, verbose_name='Ginning Name')),
                ('net_weight', models.FloatField(verbose_name='Net Weight (kg)')),
                ('date_of_unloading', models.DateTimeField(default=django.utils.timezone.now)),
                ('cotton_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_unloading', to='CottonApp.cottondata')),
            ],
            options={
                'verbose_name': 'Vehicle Unloading Data',
                'verbose_name_plural': 'Vehicle Unloading Data',
            },
        ),
    ]
