# Generated by Django 5.2.7 on 2025-10-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Farmer Name'),
        ),
    ]
