# Generated by Django 5.2.7 on 2025-10-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CottonApp', '0002_alter_customerdata_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdata',
            options={'verbose_name': 'Farmer Data', 'verbose_name_plural': 'Farmer Data'},
        ),
    ]
