# Generated by Django 5.2.7 on 2025-10-29 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonApp', '0003_alter_customerdata_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleunloadingdata',
            old_name='ginning_Name',
            new_name='ginning_name',
        ),
        migrations.RenameField(
            model_name='vehicleunloadingdata',
            old_name='Loaded_vehicle_weight',
            new_name='loaded_vehicle_weight',
        ),
        migrations.RenameField(
            model_name='vehicleunloadingdata',
            old_name='Unloading_vehicle_weight',
            new_name='unloading_vehicle_weight',
        ),
        migrations.RemoveField(
            model_name='vehicleunloadingdata',
            name='cotton_entry',
        ),
        migrations.AddField(
            model_name='cottondata',
            name='unloading_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotton_entry', to='CottonApp.vehicleunloadingdata'),
        ),
        migrations.AddField(
            model_name='vehicleunloadingdata',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unloading_entries', to='CottonApp.driverdata'),
        ),
        migrations.AlterField(
            model_name='cottondata',
            name='total_amount',
            field=models.FloatField(default=0, verbose_name='Total Amount (₹)'),
        ),
        migrations.AlterField(
            model_name='driverdata',
            name='vehicle_weight',
            field=models.FloatField(verbose_name='Empty Vehicle Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='vehicleunloadingdata',
            name='net_weight',
            field=models.FloatField(default=0, verbose_name='Net Weight (kg)'),
        ),
    ]
