# Generated by Django 5.2.7 on 2025-10-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonApp', '0004_rename_ginning_name_vehicleunloadingdata_ginning_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdata',
            name='vehicle_weight',
            field=models.FloatField(verbose_name=' Vehicle Weight (kg)'),
        ),
    ]
