# Generated by Django 5.2.7 on 2025-11-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GransData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100, verbose_name='Farmer Name')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('driver_name', models.CharField(max_length=50, verbose_name='Driver Name')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='Vehicle Number')),
                ('driver_mobile_number', models.CharField(max_length=20, verbose_name='Driver Mobile Number')),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('loaded_vehicle_weight', models.FloatField(verbose_name='Loaded Vehicle Weight (kg)')),
                ('unloading_vehicle_weight', models.FloatField(verbose_name='Unloading Vehicle Weight (kg)')),
                ('net_weight', models.FloatField(default=0, verbose_name='Net Weight (kg)')),
                ('date_of_unloading', models.DateTimeField(auto_now_add=True)),
                ('market_rate', models.FloatField(verbose_name='Market Rate (₹ per Quintal)')),
                ('total_amount', models.FloatField(default=0, verbose_name='Total Amount (₹)')),
                ('advance_paid', models.FloatField(default=0, verbose_name='Advance Paid (₹)')),
                ('balance_amount', models.FloatField(default=0, verbose_name='Balance Amount (₹)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payment Received (Cash)')),
            ],
            options={
                'verbose_name': 'Grains Data',
                'verbose_name_plural': 'Grains Data',
            },
        ),
    ]
