# Generated by Django 5.2.7 on 2025-11-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KUBS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gransdata',
            name='type_of_grain',
            field=models.CharField(default='Grain', max_length=50, verbose_name='Type of Grain'),
        ),
    ]
