# Generated by Django 5.2.7 on 2025-11-06 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KUBS', '0003_alter_gransdata_type_of_grain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GransData',
        ),
    ]
