# Generated by Django 5.2.7 on 2025-11-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KUBS', '0004_delete_gransdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='KUBS_Grains_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmers_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('driver_name', models.TextField(blank=True, null=True)),
                ('driver_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('grain_type', models.CharField(choices=[('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Pulses', 'Pulses'), ('Maize', 'Maize'), ('Tur', 'Tur'), ('Soyabean', 'Soyabean'), ('Chana', 'Chana')], max_length=20)),
                ('buyer_name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('market_rate', models.FloatField()),
                ('bedding_rate', models.FloatField()),
                ('perbag_weight', models.FloatField()),
                ('price_quintal', models.FloatField()),
                ('advance_amount', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('balance_amount', models.FloatField()),
                ('date_of_transaction', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
