# Generated by Django 5.2.7 on 2025-11-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KUBS', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kubs_grains_data',
            name='price_quintal',
        ),
    ]
