# Generated by Django 5.2.7 on 2025-11-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KUBS', '0006_remove_kubs_grains_data_price_quintal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubs_grains_data',
            name='balance_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kubs_grains_data',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
