# Generated by Django 5.2.7 on 2025-11-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KUBS', '0007_alter_kubs_grains_data_balance_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kubs_grains_data',
            name='perbag_weight',
        ),
        migrations.AlterField(
            model_name='kubs_grains_data',
            name='balance_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kubs_grains_data',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
